docs_dir: docs/book
site_dir: docs/html
extra:
  project: Headless Platform
  current_version: v1
  versions:
    - v1
nav:
  - Home: index.md
  - v1:
      - Introduction: v1/introduction.md
      - API:
          - "Introduction": v1/api/introduction.md
          - "Usage": v1/api/usage.md
      - Admin:
          - "Introduction": v1/admin/introduction.md
          - "Usage": v1/admin/usage.md
      - Core:
          - "Introduction": v1/core/introduction.md
          - "Creation": v1/core/creation.md
          - "Usage": v1/core/usage.md
          - "Benefits": v1/core/benefits.md
      - Other:
          - "Config Provider":
              - "Introduction": v1/other/config-provider/introduction.md
              - "Functionality": v1/other/config-provider/functionality.md
              - "Benefits": v1/other/config-provider/benefits.md
site_name: "Dotkernel Headless Platform"
site_description: "Dotkernel Headless Platform"
repo_url: "https://github.com/dotkernel/headless-documentation"
plugins:
  - search
